# Generated by Django 5.2 on 2025-06-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0004_alter_task_assignee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="column",
            name="title",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=64),
        ),
    ]
