# Generated by Django 5.2 on 2025-06-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0005_alter_column_title_alter_task_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("LOW", "Низкий"), ("MEDIUM", "Средний"), ("HIGH", "Высокий")],
                default="MEDIUM",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("BACKLOG", "Бэклог"),
                    ("TODO", "К выполнению"),
                    ("IN_PROGRESS", "В работе"),
                    ("REVIEW", "На проверке"),
                    ("DONE", "Выполнено"),
                    ("ARCHIVED", "В архиве"),
                ],
                default="BACKLOG",
                max_length=32,
            ),
        ),
    ]
