# Generated by Django 5.2 on 2025-07-03 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0006_alter_task_priority_alter_task_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="board",
            options={"verbose_name": "Таблица", "verbose_name_plural": "Таблицы"},
        ),
        migrations.AlterModelOptions(
            name="column",
            options={
                "ordering": ["order"],
                "verbose_name": "Колонка",
                "verbose_name_plural": "Колонки",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "Проект", "verbose_name_plural": "Проекты"},
        ),
        migrations.AlterModelOptions(
            name="relationtask",
            options={
                "verbose_name": "Связанная задача",
                "verbose_name_plural": "Связанные задачи",
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name": "Задача", "verbose_name_plural": "Задачи"},
        ),
    ]
