# Generated by Django 5.2 on 2025-09-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0007_alter_board_options_alter_column_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="board",
            options={"verbose_name": "Доска", "verbose_name_plural": "Досоки"},
        ),
    ]
