# Generated by Django 5.2 on 2025-10-02 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0008_alter_board_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="column",
            index=models.Index(
                fields=["board", "order"], name="idx_column_board_order"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["column", "status", "priority"], name="idx_task_col_stat_prio"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["assignee", "status"], name="idx_task_assignee_status"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["parent"], name="idx_task_parent"),
        ),
    ]
