global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django-app'
    static_configs:
      - targets: ['backend:8000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']