from . import base

DEBUG = False

DATABASES = base.DATABASES
INSTALLED_APPS = base.INSTALLED_APPS
MIDDLEWARE = base.MIDDLEWARE
ALLOWED_HOSTS = base.ALLOWED_HOSTS
SECRET_KEY = base.SECRET_KEY
STATIC_URL = base.STATIC_URL
DEFAULT_AUTO_FIELD = base.DEFAULT_AUTO_FIELD
