# Generated by Django 5.2 on 2025-05-28 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("phone", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="phonecode",
            table="phone_codes",
        ),
    ]
