# Generated by Django 5.2 on 2025-06-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phone", "0002_alter_phonecode_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonecode",
            name="attempts",
            field=models.IntegerField(default=0),
        ),
    ]
