# Generated by Django 5.2 on 2025-07-03 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("phone", "0003_phonecode_attempts"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="phonecode",
            options={
                "verbose_name": "Телефонный код",
                "verbose_name_plural": "Телефонные коды",
            },
        ),
    ]
