# Generated by Django 5.2 on 2025-06-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationmodel",
            name="type",
            field=models.CharField(
                choices=[
                    ("MESSAGE", "Новое сообщение в проекте"),
                    ("PROJECT_INVITE", "Приглашение в проект: {}"),
                    ("TASK_ASSIGNED", "Вам назначена задача: {}"),
                ],
                default="MESSAGE",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="notificationmodel",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
