# Generated by Django 5.2 on 2025-06-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0002_notificationmodel_type_notificationmodel_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notificationmodel",
            old_name="description",
            new_name="message",
        ),
        migrations.AlterField(
            model_name="notificationmodel",
            name="title",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
