# Generated by Django 5.2 on 2025-06-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0003_rename_description_notificationmodel_message_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificationmodel",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
            },
        ),
        migrations.AlterField(
            model_name="notificationmodel",
            name="is_read",
            field=models.BooleanField(
                default=False, help_text="Прочитано ли уведомление"
            ),
        ),
        migrations.AlterField(
            model_name="notificationmodel",
            name="message",
            field=models.TextField(
                help_text="Основной текст уведомления", max_length=2048
            ),
        ),
        migrations.AlterField(
            model_name="notificationmodel",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Краткий заголовок уведомления (автозаполняется из типа уведомления)",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="notificationmodel",
            name="url",
            field=models.URLField(
                blank=True, help_text="Ссылка для перехода при клике", null=True
            ),
        ),
    ]
