# Generated by Django 5.2 on 2025-06-18 22:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0004_alter_notificationmodel_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NotificationModel",
            new_name="Notification",
        ),
    ]
