# Generated by Django 5.2 on 2025-06-18 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0005_rename_notificationmodel_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "show_unread_only",
                    models.BooleanField(
                        default=False,
                        help_text="Скрывать прочитанные уведомления",
                        verbose_name="Только непрочитанные",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройка уведомлений",
                "verbose_name_plural": "Настройки уведомлений",
                "db_table": "notifications_settings",
            },
        ),
    ]
