# Generated by Django 5.2 on 2025-10-02 10:16

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0006_notificationsettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notification",
            index=django.contrib.postgres.indexes.BrinIndex(
                fields=["created_at"], name="idx_notification_created_brin"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "created_at"], name="idx_notification_user_created"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                condition=models.Q(("is_read", False)),
                fields=["user", "created_at"],
                name="idx_notification_unread",
            ),
        ),
    ]
