# Generated by Django 5.2 on 2025-06-02 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="board",
            table="management_boards",
        ),
        migrations.AlterModelTable(
            name="column",
            table="management_columns",
        ),
        migrations.AlterModelTable(
            name="project",
            table="management_projects",
        ),
        migrations.AlterModelTable(
            name="task",
            table="management_tasks",
        ),
        migrations.AlterModelTable(
            name="taskrelation",
            table="management_relation_tasks",
        ),
    ]
