# Generated by Django 5.2 on 2025-06-07 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project_management", "0002_alter_board_table_alter_column_table_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TaskRelation",
            new_name="RelationTask",
        ),
    ]
