# Generated by Django 5.2 on 2025-06-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="column",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="column",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
