# Generated by Django 5.2 on 2025-07-03 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification_preferences", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificationpreferences",
            options={
                "verbose_name": "Внешняя настройка уведомлений",
                "verbose_name_plural": "Внешние настройки уведомлений",
            },
        ),
    ]
